$(document).ready(function() {


$("#side1").click(function(){
$("#side1").hide();
});
$("#side1").click(function(){
$("#side2").show();
});
$("#side1").click(function(){
$("#pt1").show();
});
$("#side1").click(function(){
$("#text1").show();
});

$("#side2").click(function(){
$("#side2").hide();
});
$("#side2").click(function(){
$("#side3").show();
});
$("#side2").click(function(){
$("#pt2").show();
});
$("#side2").click(function(){
$("#pt1").hide();
});
$("#side2").click(function(){
$("#text2").show();
});
$("#side2").click(function(){
$("#text1").hide();
});

$("#side3").click(function(){
$("#side3").hide();
});
$("#side3").click(function(){
$("#side4").show();
});
$("#side3").click(function(){
$("#pt3").show();
});
$("#side3").click(function(){
$("#pt2").hide();
});
$("#side3").click(function(){
$("#text3").show();
});
$("#side3").click(function(){
$("#text2").hide();
});

$("#side4").click(function(){
$("#side4").hide();
});
$("#side4").click(function(){
$("#side5").show();
});
$("#side4").click(function(){
$("#pt4").show();
});
$("#side4").click(function(){
$("#pt3").hide();
});
$("#side4").click(function(){
$("#text4").show();
});
$("#side4").click(function(){
$("#text3").hide();
});

$("#side5").click(function(){
$("#side5").hide();
});
$("#side5").click(function(){
$("#side6").show();
});
$("#side5").click(function(){
$("#pt5").show();
});
$("#side5").click(function(){
$("#pt4").hide();
});
$("#side5").click(function(){
$("#text5").show();
});
$("#side5").click(function(){
$("#text4").hide();
});

$("#side6").click(function(){
$("#side6").hide();
});
$("#side6").click(function(){
$("#side1").show();
});
$("#side6").click(function(){
$("#pt6").show();
});
$("#side6").click(function(){
$("#pt5").hide();
});
$("#side6").click(function(){
$("#text6").show();
});
$("#side6").click(function(){
$("#text5").hide();
});

$("#side1").click(function(){
$("#pt6").hide();
});
$("#side1").click(function(){
$("#text6").hide();
});


})
